Revert "Import constants from common instead of openvswitch."
This reverts commit 1517db5b4e4bb1ed74263ea5ec4f185c0cd2a6ab.

Make this work for Havana where odl_ml2 driver hits this error:

2014-04-25 14:47:07.468 3875 ERROR neutron.plugins.ml2.managers [-] Mechanism driver opendaylight failed in bind_port
2014-04-25 14:47:07.468 3875 TRACE neutron.plugins.ml2.managers Traceback (most recent call last):
...
2014-04-25 14:47:07.468 3875 TRACE neutron.plugins.ml2.managers if network_type in [constants.TYPE_LOCAL, constants.TYPE_FLAT,
2014-04-25 14:47:07.468 3875 TRACE neutron.plugins.ml2.managers AttributeError: 'module' object has no attribute 'TYPE_LOCAL'

Signed-off-by: Chris Wright <chrisw@sous-sol.org>